
resources:
  # Step 1: Enable essential APIs
  - name: enable-apis
    type: gcp-types/compute-v1:compute.projects.setCommonInstanceMetadata
    properties:
      metadata:
        items:
          - key: enable-apis
            value: |
              compute.googleapis.com
              cloudresourcemanager.googleapis.com
              servicenetworking.googleapis.com
              bigquery.googleapis.com
              sqladmin.googleapis.com
              iam.googleapis.com
              datastream.googleapis.com
              deploymentmanager.googleapis.com

  # Step 2: Create VPC network
  - name: migration-vpc
    type: compute.v1.network
    properties:
      name: migration-vpc-431312  # Custom name with your project identifier
      autoCreateSubnetworks: false

  # Step 3: Create Subnet
  - name: subnet-1
    type: compute.v1.subnetwork
    properties:
      name: subnet-1-431312  # Custom name with your project identifier
      ipCidrRange: 10.0.0.0/24
      region: asia-south1
      network: $(ref.migration-vpc.selfLink)

  # Step 4: Create Firewall Rule for SSH (port 22) and ICMP
  - name: allow-ssh-and-icmp
    type: compute.v1.firewall
    properties:
      network: $(ref.migration-vpc.selfLink)
      allowed:
        - IPProtocol: TCP
          ports: ["22"]
        - IPProtocol: ICMP
      sourceRanges: ["35.235.240.0/20", "0.0.0.0/0"]
      targetTags: ["allow-ssh-icmp"]

  # Step 5: Reserve Static External IP
  - name: static-ip
    type: compute.v1.address
    properties:
      name: static-ip-431312  # Custom name with your project identifier
      region: asia-south1

  # Step 6: Create Cloud Router
  - name: cloud-router
    type: compute.v1.router
    properties:
      name: cloud-router-431312  # Custom name with your project identifier
      region: asia-south1
      network: $(ref.migration-vpc.selfLink)
      bgp:
        asn: 65001

  # Step 7: Create VPN Gateway
  - name: vpn-gateway
    type: compute.v1.vpnGateway
    properties:
      name: vpn-gateway-431312  # Custom name with your project identifier
      region: asia-south1
      network: $(ref.migration-vpc.selfLink)
      interface:
        - ipAddress: $(ref.static-ip.address)
          region: asia-south1

outputs:
  - name: vpnGatewayIP
    value: $(ref.vpn-gateway.networkInterfaces[0].ipAddress)
  - name: staticIP
    value: $(ref.static-ip.address)
