name: GCP Infrastructure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'gcloud'

    - name: Enable Deployment Manager API
      run: gcloud services enable deploymentmanager.googleapis.com

    - name: Deploy Infrastructure
      run: gcloud deployment-manager deployments create migration-infra --config ./infra/deployment.yaml
  # Using --source instead of --config   #updated

